/**
 * Pull request creation and updates
 */

import { workerLogger } from '../../logging/index.js';
import type { CodeMetadata } from '../../gemini-agent/shared/code_metadata.js';
import { GITHUB_API_URL, DEFAULT_BASE_BRANCH } from '../constants.js';
import { serializeError } from '../logging/errors.js';
import { formatSummaryForPr } from './autoCommit.js';

// Re-export for use in other modules
export { formatSummaryForPr };

/**
 * Parse GitHub repository info from remote URL
 */
function parseGithubRepo(remoteUrl: string | undefined, branchName: string): { owner: string; repo: string; head: string } | null {
  const normalizeRepository = (value?: string | null): string | null => {
    if (!value) return null;
    const trimmed = value.trim().replace(/\.git$/i, '');
    if (!trimmed.includes('/')) return null;
    return trimmed;
  };

  const inferRepositoryFromRemote = (url?: string): string | null => {
    if (!url) return null;

    // SSH form: git@host:owner/repo.git
    const sshMatch = url.match(/^git@([^:]+?):(.+?)$/);
    if (sshMatch) {
      return normalizeRepository(sshMatch[2]);
    }

    // Handle scp-like shorthand without scheme: host:owner/repo.git
    const scpMatch = url.match(/^([^@]+?):(.+?)$/);
    if (scpMatch && !url.includes('://')) {
      return normalizeRepository(scpMatch[2]);
    }

    // URL forms: https://host/owner/repo.git or ssh://
    try {
      const parsed = new URL(url);
      const pathname = parsed.pathname.replace(/^\/+/, '');
      return normalizeRepository(pathname);
    } catch {
      return null;
    }
  };

  const repository = normalizeRepository(process.env.GITHUB_REPOSITORY) ?? inferRepositoryFromRemote(remoteUrl);
  if (!repository) return null;

  const [owner, repo] = repository.split('/', 2);
  if (!owner || !repo) return null;
  return { owner, repo, head: `${owner}:${branchName}` };
}

/**
 * Create or update pull request for job branch
 */
export async function createOrUpdatePullRequest(params: {
  codeMetadata: CodeMetadata;
  branchName: string;
  baseBranch: string;
  requestId: string;
  summaryBlock?: string;
}): Promise<string | null> {
  const { codeMetadata, branchName, baseBranch, requestId, summaryBlock } = params;
  const token = process.env.GITHUB_TOKEN;
  if (!token) {
    workerLogger.warn('Missing GITHUB_TOKEN; skipping PR creation');
    return null;
  }

  const repoInfo = parseGithubRepo(codeMetadata.repo?.remoteUrl || codeMetadata.branch.remoteUrl, branchName);
  if (!repoInfo) {
    workerLogger.warn('Unable to infer GitHub repository from remote; skipping PR creation');
    return null;
  }

  const headers = {
    Authorization: `Bearer ${token}`,
    Accept: 'application/vnd.github+json',
    'User-Agent': 'jinn-mech-worker',
  };

  const searchUrl = `${GITHUB_API_URL}/repos/${repoInfo.owner}/${repoInfo.repo}/pulls?head=${encodeURIComponent(repoInfo.head)}&state=open`;
  try {
    const res = await fetch(searchUrl, { headers });
    if (res.ok) {
      const data = await res.json();
      if (Array.isArray(data) && data.length > 0) {
        workerLogger.info({ branchName, pr: data[0]?.number }, 'Existing PR found for branch');
        return data[0]?.html_url || null;
      }
    } else {
      workerLogger.warn({ status: res.status, statusText: res.statusText }, 'Failed to query existing PRs');
    }
  } catch (error) {
    workerLogger.warn({ error: serializeError(error) }, 'Error querying GitHub for existing PR');
  }

  const title = `[Job ${codeMetadata.jobDefinitionId}] updates`;
  const bodyLines = [
    `Automated PR for job definition ${codeMetadata.jobDefinitionId}.`,
    '',
    `- Request ID: ${requestId}`,
    `- Branch: \`${branchName}\``,
    `- Base: \`${baseBranch}\``,
    '',
    'This PR was generated by the mech worker after successful validation.',
  ];
  
  // Add execution summary if provided
  const formattedSummary = summaryBlock || formatSummaryForPr(null);
  if (formattedSummary) {
    bodyLines.push('', formattedSummary);
  }

  try {
    const res = await fetch(`${GITHUB_API_URL}/repos/${repoInfo.owner}/${repoInfo.repo}/pulls`, {
      method: 'POST',
      headers: {
        ...headers,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        title,
        head: branchName,
        base: baseBranch,
        body: bodyLines.join('\n'),
      }),
    });

    if (!res.ok) {
      const text = await res.text();
      throw new Error(`GitHub PR creation failed (${res.status}): ${text}`);
    }
    const data = await res.json();
    const prUrl = data?.html_url as string | undefined;
    workerLogger.info({ branchName, prUrl }, 'Created GitHub PR');
    return prUrl || null;
  } catch (error) {
    workerLogger.error({
      error: error instanceof Error ? error.message : String(error),
      stack: error instanceof Error ? error.stack : undefined,
      raw: error
    }, 'Failed to create pull request');
    return null;
  }
}

