version: '2.4'
services:
  memeooorr0scH_tm_0:
    user: '1000'
    mem_limit: 1024m
    mem_reservation: 256M
    cpus: 0.5
    container_name: memeooorr0scH_tm_0
    hostname: memeooorr0scH_tm_0
    image: valory/open-autonomy-tendermint:0.20.2
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 10m
    environment:
    - ID=0
    - PROXY_APP=tcp://memeooorr0scH_abci_0:26658
    - TMHOME=/tendermint/node0
    - CREATE_EMPTY_BLOCKS=true
    - DEV_MODE=0
    - LOG_FILE=/logs/node_0.txt
    - LOG_LEVEL=INFO
    - WRITE_TO_LOG=true
    working_dir: /tendermint
    command:
    - run
    - --no-reload
    - --host=0.0.0.0
    - --port=8080
    depends_on:
      memeooorr0scH_abci_0:
        condition: service_healthy
    networks:
      service_memeooorr0scH_localnet:
        ipv4_address: 192.167.19.3
    volumes:
    - ./nodes:/tendermint:Z
    - ./persistent_data/logs:/logs:Z
  memeooorr0scH_abci_0:
    mem_reservation: 256M
    mem_limit: 1024M
    cpus: 1.0
    container_name: memeooorr0scH_abci_0
    image: dvilela/oar-memeooorr:bafybeihxlzohhj5o3fjf6x5n3kwsvcwx54go4qfh26qw2zhytxwobysxau
    env_file: agent_0.env
    user: '501:20'
    logging:
      driver: json-file
      options:
        max-size: 10m
    networks:
      service_memeooorr0scH_localnet:
        ipv4_address: 192.167.19.2
    extra_hosts:
    - host.docker.internal:host-gateway
    volumes:
    - ./persistent_data/logs:/logs:Z
    - ./agent_keys/agent_0:/agent_key:Z
    - ../persistent_data:/data:Z
    ports:
    - 8716:8716
networks:
  service_memeooorr0scH_localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.167.19.0/24
