export const ADWDocumentRegistryABI = [
  {
    inputs: [{ internalType: 'string', name: 'name_', type: 'string' }, { internalType: 'string', name: 'symbol_', type: 'string' }, { internalType: 'address', name: 'owner_', type: 'address' }],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  { inputs: [{ internalType: 'bytes32', name: 'contentHash', type: 'bytes32' }], name: 'ContentHashAlreadyRegistered', type: 'error' },
  { inputs: [], name: 'ContractPaused', type: 'error' },
  { inputs: [{ internalType: 'uint256', name: 'documentId', type: 'uint256' }], name: 'DocumentDoesNotExist', type: 'error' },
  { inputs: [], name: 'EmptyURI', type: 'error' },
  { inputs: [{ internalType: 'uint256', name: 'documentId', type: 'uint256' }, { internalType: 'address', name: 'caller', type: 'address' }], name: 'NotDocumentOwner', type: 'error' },
  { inputs: [{ internalType: 'address', name: 'sender', type: 'address' }, { internalType: 'address', name: 'owner', type: 'address' }], name: 'OwnerOnly', type: 'error' },
  { inputs: [], name: 'ZeroAddress', type: 'error' },
  { inputs: [], name: 'ZeroContentHash', type: 'error' },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'documentId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'creator', type: 'address' },
      { indexed: false, internalType: 'string', name: 'documentType', type: 'string' },
      { indexed: false, internalType: 'string', name: 'documentURI', type: 'string' },
      { indexed: false, internalType: 'bytes32', name: 'contentHash', type: 'bytes32' },
      { indexed: false, internalType: 'uint256', name: 'timestamp', type: 'uint256' },
    ],
    name: 'DocumentRegistered',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'documentId', type: 'uint256' },
      { indexed: false, internalType: 'string', name: 'newDocumentURI', type: 'string' },
    ],
    name: 'DocumentURIUpdated',
    type: 'event',
  },
  {
    inputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    name: 'contentHashToDocumentId',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'documentContentHashes',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'name',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
    name: 'ownerOf',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'paused',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'string', name: 'documentURI', type: 'string' },
      { internalType: 'bytes32', name: 'contentHash', type: 'bytes32' },
      { internalType: 'string', name: 'documentType', type: 'string' },
    ],
    name: 'register',
    outputs: [{ internalType: 'uint256', name: 'documentId', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'documentId', type: 'uint256' }],
    name: 'resolve',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'documentId', type: 'uint256' }, { internalType: 'string', name: 'newURI', type: 'string' }],
    name: 'setDocumentURI',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalDocuments',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
    name: 'tokenURI',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
] as const

export const ADWReputationRegistryABI = [
  {
    inputs: [{ internalType: 'address', name: '_documentRegistry', type: 'address' }],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  { inputs: [{ internalType: 'uint256', name: 'documentId', type: 'uint256' }], name: 'DocumentDoesNotExist', type: 'error' },
  { inputs: [], name: 'ZeroAddress', type: 'error' },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'documentId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'sender', type: 'address' },
      { indexed: false, internalType: 'int128', name: 'score', type: 'int128' },
      { indexed: false, internalType: 'uint8', name: 'decimals', type: 'uint8' },
      { indexed: false, internalType: 'string', name: 'tag1', type: 'string' },
      { indexed: false, internalType: 'string', name: 'tag2', type: 'string' },
      { indexed: false, internalType: 'string', name: 'feedbackURI', type: 'string' },
      { indexed: false, internalType: 'bytes32', name: 'feedbackHash', type: 'bytes32' },
      { indexed: false, internalType: 'uint256', name: 'timestamp', type: 'uint256' },
    ],
    name: 'FeedbackGiven',
    type: 'event',
  },
  {
    inputs: [],
    name: 'documentRegistry',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'unitId', type: 'uint256' },
      { internalType: 'int128', name: 'score', type: 'int128' },
      { internalType: 'uint8', name: 'decimals', type: 'uint8' },
      { internalType: 'string', name: 'tag1', type: 'string' },
      { internalType: 'string', name: 'tag2', type: 'string' },
      { internalType: 'string', name: 'endpoint', type: 'string' },
      { internalType: 'string', name: 'feedbackURI', type: 'string' },
      { internalType: 'bytes32', name: 'feedbackHash', type: 'bytes32' },
    ],
    name: 'giveFeedback',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
] as const

export const ADWValidationRegistryABI = [
  {
    inputs: [{ internalType: 'address', name: '_documentRegistry', type: 'address' }],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  { inputs: [{ internalType: 'uint256', name: 'documentId', type: 'uint256' }], name: 'DocumentDoesNotExist', type: 'error' },
  { inputs: [{ internalType: 'address', name: 'caller', type: 'address' }, { internalType: 'address', name: 'validator', type: 'address' }], name: 'NotDesignatedValidator', type: 'error' },
  { inputs: [{ internalType: 'bytes32', name: 'requestHash', type: 'bytes32' }], name: 'RequestAlreadyResponded', type: 'error' },
  { inputs: [{ internalType: 'bytes32', name: 'requestHash', type: 'bytes32' }], name: 'RequestNotFound', type: 'error' },
  { inputs: [], name: 'ZeroAddress', type: 'error' },
  { inputs: [], name: 'ZeroRequestHash', type: 'error' },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'validator', type: 'address' },
      { indexed: true, internalType: 'uint256', name: 'documentId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'requester', type: 'address' },
      { indexed: false, internalType: 'string', name: 'requestURI', type: 'string' },
      { indexed: false, internalType: 'bytes32', name: 'requestHash', type: 'bytes32' },
      { indexed: false, internalType: 'uint256', name: 'timestamp', type: 'uint256' },
    ],
    name: 'ValidationRequested',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'bytes32', name: 'requestHash', type: 'bytes32' },
      { indexed: true, internalType: 'address', name: 'validator', type: 'address' },
      { indexed: false, internalType: 'uint8', name: 'response', type: 'uint8' },
      { indexed: false, internalType: 'string', name: 'responseURI', type: 'string' },
      { indexed: false, internalType: 'bytes32', name: 'responseHash', type: 'bytes32' },
      { indexed: false, internalType: 'string', name: 'tag', type: 'string' },
      { indexed: false, internalType: 'uint256', name: 'timestamp', type: 'uint256' },
    ],
    name: 'ValidationResponded',
    type: 'event',
  },
  {
    inputs: [],
    name: 'documentRegistry',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    name: 'requestResponded',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    name: 'requestValidators',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'validator', type: 'address' },
      { internalType: 'uint256', name: 'unitId', type: 'uint256' },
      { internalType: 'string', name: 'requestURI', type: 'string' },
      { internalType: 'bytes32', name: 'requestHash', type: 'bytes32' },
    ],
    name: 'validationRequest',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: 'requestHash', type: 'bytes32' },
      { internalType: 'uint8', name: 'response', type: 'uint8' },
      { internalType: 'string', name: 'responseURI', type: 'string' },
      { internalType: 'bytes32', name: 'responseHash', type: 'bytes32' },
      { internalType: 'string', name: 'tag', type: 'string' },
    ],
    name: 'validationResponse',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
] as const
